antiAffinity: "soft"
imageTag: "6.8.1"
clusterName: "elasticsearchdb"
esConfig:
  elasticsearch.yml: |
    http:
      cors: 
        enabled: true
        allow-origin: "*" 
        allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
        allow-headers: "X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization"
