keycloak:
  password: qsopjk9cL6
  extraVolumes: |
    - name: realm-secret
      secret:
        secretName: realm-secret
    - name: theme
      emptyDir: {}

  extraVolumeMounts: |
    - name: realm-secret
      mountPath: "/realm/"
      readOnly: true
    - name: theme
      mountPath: /opt/jboss/keycloak/themes/mytheme

  extraArgs: -Dkeycloak.import=/realm/realm.json
  extraInitContainers: |
    - name: theme-provider
      image: docker.io/salientcrgt2/scrgt-bdso-keycloak-theme
      imagePullPolicy: Always
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /celebs_themes/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme
