---

- name: celebrity job
  jenkins_job:
    config: "{{ lookup('template', 'templates/celebrity.xml') }}"
    name: celebrity_ms
    password: "{{ jenkins_admin_password }}"
    url: "{{jenkins_url}}:{{ jenkins_port }}"
    user: "{{ jenkins_admin_username }}"

- name: frontend job
  jenkins_job:
    config: "{{ lookup('template', 'templates/frontend.xml') }}"
    name: frontend_ms
    password: "{{ jenkins_admin_password }}"
    url: "{{jenkins_url}}:{{ jenkins_port }}"
    user: "{{ jenkins_admin_username }}"

- name: recommendation job
  jenkins_job:
    config: "{{ lookup('template', 'templates/recommendation.xml') }}"
    name: recommendation_ms
    password: "{{ jenkins_admin_password }}"
    url: "{{jenkins_url}}:{{ jenkins_port }}"
    user: "{{ jenkins_admin_username }}"

- name: data pipeline job
  jenkins_job:
    config: "{{ lookup('template', 'templates/datapipeline.xml') }}"
    name: datapipeline
    password: "{{ jenkins_admin_password }}"
    url: "{{jenkins_url}}:{{ jenkins_port }}"
    user: "{{ jenkins_admin_username }}"

- name: nightly data load job
  jenkins_job:
    config: "{{ lookup('template', 'templates/nightlydataload.xml') }}"
    name: nightlydataload
    password: "{{ jenkins_admin_password }}"
    url: "{{jenkins_url}}:{{ jenkins_port }}"
    user: "{{ jenkins_admin_username }}"