
ALTER TABLE ACTORS
ADD COLUMN HEIGHT	INT,
ADD COLUMN BIRTH_PLACE	 VARCHAR(200),
ADD COLUMN DOB	  DATE,
ADD COLUMN NICK_NAME VARCHAR(100),
ADD COLUMN POPULARITY INT,
ADD COLUMN BIOGRAPHY VARCHAR(4000),
ADD COLUMN EXT_PHOTO_ID VARCHAR(100),
ADD COLUMN IMAGE_URL	VARCHAR(1000),
ADD COLUMN ACTOR_ATTRIB JSONB;