
CREATE TABLE IF NOT EXISTS MOVIE_CAST
(
    ID      SERIAL      NOT NULL,
    MOV_ID   INT    NOT NULL,
    ACT_ID   INT    NOT NULL,
    ROLE_NAME   VARCHAR(200),
    DESCRIPTION VARCHAR(4000),
    CONSTRAINT PK_MOV_CAST PRIMARY KEY (ID)
);

ALTER TABLE MOVIE_CAST 
ADD CONSTRAINT FK_MOV_CAST1 FOREIGN KEY (MOV_ID) REFERENCES MOVIES (ID);

ALTER TABLE MOVIE_CAST 
ADD CONSTRAINT FK_MOV_CAST2 FOREIGN KEY (ACT_ID) REFERENCES ACTORS (ID);