
CREATE TABLE IF NOT EXISTS MOVIE_GENRES
(
    ID      SERIAL      NOT NULL,
    MOV_ID   INT,
    GENRE VARCHAR(200) NOT NULL,
    CONSTRAINT PK_MOV_GENRE PRIMARY KEY (ID)
);

ALTER TABLE MOVIE_GENRES 
ADD CONSTRAINT FK_MOV_GENRE FOREIGN KEY (MOV_ID) REFERENCES MOVIES (ID);