
CREATE TABLE IF NOT EXISTS ACTORS
(
    ID      SERIAL      NOT NULL,
    FIRST_NAME   VARCHAR(200)    NOT NULL,
    LAST_NAME   VARCHAR(200)    NOT NULL,
    GENDER   CHARACTER VARYING(6),
    BOX_OFFICE	BIGINT,
    NUM_MOVIES	INT,
    AVG_REVENUE BIGINT,
    IMDB_ID INT NOT NULL,
    MOVDB_ID INT NOT NULL,
    CONSTRAINT PK_ACTORS PRIMARY KEY (ID)
);