
CREATE TABLE IF NOT EXISTS MOVIE_PRODUCTION
(
    ID      SERIAL      NOT NULL,
    MOV_ID   INT    NOT NULL,
    COMP_ID   INT    NOT NULL,
    CONSTRAINT PK_MOV_PROD PRIMARY KEY (ID)
);

ALTER TABLE MOVIE_PRODUCTION 
ADD CONSTRAINT FK_MOV_PROD1 FOREIGN KEY (MOV_ID) REFERENCES MOVIES (ID);

ALTER TABLE MOVIE_PRODUCTION 
ADD CONSTRAINT FK_MOV_PROD2 FOREIGN KEY (COMP_ID) REFERENCES COMPANIES (ID);