
CREATE TABLE IF NOT EXISTS MOVIES
(
    ID      SERIAL      NOT NULL,
    TITLE   VARCHAR(500)    NOT NULL,
    BUDGET  INT,
    HOME_PAGE VARCHAR(2000),
    ORIG_LANGUAGE VARCHAR(200),
    ORIG_TITLE VARCHAR(500),
    OVERVIEW VARCHAR(500),
    POPULARITY INT,
    POSTER_IMG_ID VARCHAR(50),
    PROD_COMPANIES VARCHAR(1000),
    RELEASE_DATE DATE,
    REVENUE BIGINT,
    RUNTIME INT,
    SPOKEN_LANGUAGES VARCHAR(500),
    STATUS VARCHAR(200),
    TAGLINE VARCHAR(2000),
    RANKING INT,
    IMDB_ID INT NOT NULL,
    MOVDB_ID INT NOT NULL,
    MOV_ATTRIB JSONB,
    CONSTRAINT PK_MOVIES PRIMARY KEY (ID)
);

