
CREATE TABLE IF NOT EXISTS AUDIT_LOG
(
    ID      SERIAL      NOT NULL,
    TABLE_NAME		VARCHAR(100) 	NOT NULL,
    TABLE_ID		VARCHAR(100) 	NOT NULL,
    FIELD_NAME		VARCHAR(100) 	NOT NULL,
    CHANGE_DATE   	TIMESTAMP    	NOT NULL,
    CHANGED_BY   	VARCHAR(100)	NOT NULL,
    CHANGES			TEXT			NOT NULL,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (ID)
);